### ISSUE TITLE
FS312F-G discontinued at LCSC 

### ISSUE THREAD

**Issue by PlagueDoctor238** [hi-ban/charger-boy#1]
The Fortune Semicon FS312F-G is discontinued at LCSC. Is there a replacement that fits the same package?

**Comment by bardeci** [comment]
If you're going to solder the components yourself, you can easily find the FS312F-G for sale in aliexpress, lots of vendors sell it.

Alternatively, you should be able to use a DW01, which uses the same pinout and is available everywhere. BUT the DW01 has a different overdischarge value (2.4v instead of 2.9v), so if you use the DW01 you must also change two resistors:
R5 to 47K
R6 to 150K.

Parts list:

DW01 (LCSC part number C917079 or C181096)
47K resistor: 0805W8F4702T5E (LCSC part number C17713)
150K resistor: 0805W8F1503T5E (LCSC part number: C17470)

Hope this helps.

**Comment by PlagueDoctor238** [comment]
Thanks for your elaborate answer! 

I found it on alieexpress as you suggested.
